//
//  NowPlayingMoviesWorker.swift
//  MovieApp
//
//  Created by Thanos on 23/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SDWebImage

class NowPlayingMoviesWorker
{
    var apiManager = APIManager()
    var databaseManager = DatabaseManager()
    var imageArr = [UIImage?]()
    var count = 0
  func doSomeWork()
  {
  }
    
    func downloadNowPlayingMovies(lang: String, page: Int, category: MovieCategory, completion2: @escaping (Bool)-> Void){
        self.apiManager.fetchMovieDetails(lang: lang, page: page, category: category, completion: {
            success in
            
            if success{
                self.fetchMovies(category: category, fetchedMovies: {success in
                    
                    completion2(success)
                })
            }
        })
        
        
    }
    func downloadNowPlayingMoviesWithoutLag(lang: String, page: Int, category: MovieCategory, completion2: @escaping (Bool)-> Void){
        self.apiManager.fetchMovieDetails(lang: lang, page: page, category: category, completion: {
            success in
            
            if success{
                self.fetchMovies(category: category, fetchedMovies: {
                    success in
                    self.fetchMoviesImage()
                    completion2(success)
                })
            }
        })
    }
    
    
    func fetchMovies(category: MovieCategory, fetchedMovies: (Bool)-> Void){
        databaseManager.fetchMovieDetails(category: category, completion: {
            success in
            self.fetchMoviesImage()
            fetchedMovies(success)
        })
    }
    
    func fetchMoviesImage(){
        
        for movie in DatabaseManager.nowPlayingMovies{
            
            SDImageCache.shared.queryCacheOperation(forKey: imagDwldBaseURL+movie.posterPath!) { (image, data, cacheType) in
                if let image = image{
                    
                }
                else{
                    SDWebImageDownloader.shared.downloadImage(with: URL(string: imagDwldBaseURL+movie.posterPath!), options: SDWebImageDownloaderOptions.useNSURLCache, progress: nil) { (image, data, error, success) in
                        
                        if let image = image {
                            if success{
                                SDImageCache.shared.store(image, forKey: imagDwldBaseURL+movie.posterPath!, toDisk: true, completion: nil)
                                self.count += 1
                                print(self.count)
                            }
                        }
                        
                        
                    }
                }
                
            }
            
            
        }
    }
}
