//
//  SearchedMoviesRouter.swift
//  MovieApp
//
//  Created by Thanos on 24/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchedMoviesRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToDetailViewController()
}

protocol SearchedMoviesDataPassing
{
  var dataStore: SearchedMoviesDataStore? { get }
  var movie: Movie? { get set }
}

class SearchedMoviesRouter: NSObject, SearchedMoviesRoutingLogic, SearchedMoviesDataPassing
{
  weak var viewController: SearchedMoviesViewController?
  var dataStore: SearchedMoviesDataStore?
  var movie: Movie?
    
    
  // MARK: Routing
    
    func routeToDetailViewController() {
        let vc = UIStoryboard(name: "Main", bundle: .main).instantiateViewController(withIdentifier: "MovieDetailViewController") as! MovieDetailViewController
        vc.movie = movie
        vc.movieCategory = .none
        viewController!.navigationController?.pushViewController(vc, animated: true)
        
    }
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: SearchedMoviesViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SearchedMoviesDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
