//
//  SearchedMoviesPresenter.swift
//  MovieApp
//
//  Created by Thanos on 24/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchedMoviesPresentationLogic
{
  func presentMovies(pageCount: Int, movies: [Movie])
}

class SearchedMoviesPresenter: SearchedMoviesPresentationLogic
{
  weak var viewController: SearchedMoviesDisplayLogic?
  
  // MARK: Do something
  
    func presentMovies(pageCount: Int, movies: [Movie])
  {
    let viewModel = SearchedMovies.Something.ViewModel()
    viewController?.displayMovies(pageCount: pageCount, movies: movies)
  }
}
