//
//  SearchedMoviesWorker.swift
//  MovieApp
//
//  Created by Thanos on 24/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchedMoviesWorker
{
    var totalPageCount: Int = 1
    
  func doSomeWork()
  {
  }
    
    func fetchSearchData(searchText: String, pageCount: Int, completion : @escaping (_ success:Bool, _ totalPageCount: Int, _ movies : [Movie]) -> ()){
        let text = searchText.replacingOccurrences(of: " ", with: "+")
        
        let url = URL(string: "https://api.themoviedb.org/3/search/movie?api_key=60af9fe8e3245c53ad9c4c0af82d56d6&language=en-US&page=\(pageCount)&query=\(text)")!
        let urlRequest = URLRequest(url: url)
        let session = URLSession.shared
        let dataTask = session.dataTask(with: urlRequest) { (data, response, error) in
            
            if let error = error {
                print(error.localizedDescription)
            }else{
                if let data = data{
                    do{
                        let decoder = JSONDecoder()
                        let movieDetails = try decoder.decode(MovieResults.self, from: data)
                        self.totalPageCount = movieDetails.totalPages!
                        if let searchedMovies = movieDetails.results{
                          completion(true,self.totalPageCount,searchedMovies)
                        }
                        
                    }catch(let error){
                        print(error.localizedDescription)
                    }
                    
                }
            }
        }
        
        dataTask.resume()
    }
}
