//
//  SearchedMoviesInteractor.swift
//  MovieApp
//
//  Created by Thanos on 24/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchedMoviesBusinessLogic
{
  func doSomething(searchText: String, pageCount: Int)
}

protocol SearchedMoviesDataStore
{
  //var name: String { get set }
}

class SearchedMoviesInteractor: SearchedMoviesBusinessLogic, SearchedMoviesDataStore
{
  var presenter: SearchedMoviesPresentationLogic?
  var worker: SearchedMoviesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(searchText: String, pageCount: Int)
  {
    worker = SearchedMoviesWorker()
    worker?.fetchSearchData(searchText: searchText, pageCount: pageCount, completion: { (success, totalPageCount, movies) in
        if success {
             self.presenter?.presentMovies(pageCount: totalPageCount, movies: movies)
        }
    })
    
   
   
  }
}
