//
//  LandingSceneInteractor.swift
//  MovieApp
//
//  Created by Thanos on 24/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingSceneBusinessLogic
{
  func doSomething(request: LandingScene.Something.Request)
}

protocol LandingSceneDataStore
{
  //var name: String { get set }
}

class LandingSceneInteractor: LandingSceneBusinessLogic, LandingSceneDataStore
{
  var presenter: LandingScenePresentationLogic?
  var worker: LandingSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: LandingScene.Something.Request)
  {
    worker = LandingSceneWorker()
    worker?.doSomeWork()
    let defaults = UserDefaults.standard
    
    if !(defaults.bool(forKey: "didFetchTopRatedMoviesForFirstTime")){
        defaults.set(true, forKey: "didFetchTopRatedMoviesForFirstTime")
        worker?.downloadMovies(lang: "en-US", page: 1, category: .topRated, completion2: {
            success in
            
            if success{
                let response = LandingScene.Something.Response()
                self.presenter?.presentSomething(response: response)
            }
            
        })
    }
    else{
        worker?.fetchMovies(category: .topRated, fetchedMovies: {
            success in
            
            if success {
                let response = LandingScene.Something.Response()
                self.presenter?.presentSomething(response: response)
            }
        })
    }
    
    
  }
}
