//
//  LandingSceneViewController.swift
//  MovieApp
//
//  Created by Thanos on 24/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingSceneDisplayLogic: class
{
  func displaySomething(viewModel: LandingScene.Something.ViewModel)
}

class LandingSceneViewController: UIViewController, LandingSceneDisplayLogic
{
  var interactor: LandingSceneBusinessLogic?
  var router: (NSObjectProtocol & LandingSceneRoutingLogic & LandingSceneDataPassing)?

    @IBOutlet weak var dataLoader: UIActivityIndicatorView!
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = LandingSceneInteractor()
    let presenter = LandingScenePresenter()
    let router = LandingSceneRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    
  }
   
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.dataLoader.startAnimating()
        doSomething()
     
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = LandingScene.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: LandingScene.Something.ViewModel)
  {
    DispatchQueue.main.async {
        self.dataLoader.stopAnimating()
        self.router?.routeToRootViewController()
    }
    
  }
}
