//
//  UpcomingMoviePresenter.swift
//  MovieApp
//
//  Created by Thanos on 24/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpcomingMoviePresentationLogic
{
  func presentSomething(response: UpcomingMovie.Something.Response)
}

class UpcomingMoviePresenter: UpcomingMoviePresentationLogic
{
  weak var viewController: UpcomingMovieDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: UpcomingMovie.Something.Response)
  {
    let viewModel = DatabaseManager.upcomingMovies
    viewController?.displaySomething(viewModel: viewModel)
  }
}
