//
//  RatedMoviesPresenter.swift
//  MovieApp
//
//  Created by Thanos on 24/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RatedMoviesPresentationLogic
{
  func presentSomething(response: RatedMovies.Something.Response)
}

class RatedMoviesPresenter: RatedMoviesPresentationLogic
{
  weak var viewController: RatedMoviesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: RatedMovies.Something.Response)
  {
    let viewModel = DatabaseManager.topRatedMovies
    viewController?.displaySomething(viewModel: viewModel)
  }
}
