//
//  RatedMoviesInteractor.swift
//  MovieApp
//
//  Created by Thanos on 24/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RatedMoviesBusinessLogic
{
  func doSomething(request: RatedMovies.Something.Request)
  func callAPI(with page: Int, category: MovieCategory)
}

protocol RatedMoviesDataStore
{
  //var name: String { get set }
}

class RatedMoviesInteractor: RatedMoviesBusinessLogic, RatedMoviesDataStore
{
  var presenter: RatedMoviesPresentationLogic?
  var worker: RatedMoviesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RatedMovies.Something.Request)
  {
    worker = RatedMoviesWorker()
    worker?.doSomeWork()
    
    let response = RatedMovies.Something.Response()
    presenter?.presentSomething(response: response)
  }
    
    func callAPI(with page: Int, category: MovieCategory){
        worker?.downloadTopRatedMoviesWithoutLag(lang: "en-US", page: page, category: category, completion2: {
            success in
           
            if success {
                let response = RatedMovies.Something.Response()
                self.presenter?.presentSomething(response: response)
            }
        })
        
        
    }
}
