//
//  TopRatedMoviesInteractor.swift
//  MovieApp
//
//  Created by Thanos on 23/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopRatedMoviesBusinessLogic
{
  func doSomething(request: TopRatedMovies.Something.Request)
  func callAPI(with page: Int, category: MovieCategory)
}

protocol TopRatedMoviesDataStore
{
  //var name: String { get set }
}

class TopRatedMoviesInteractor: TopRatedMoviesBusinessLogic, TopRatedMoviesDataStore
{
  var presenter: TopRatedMoviesPresentationLogic?
  var worker: TopRatedMoviesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func doSomething(request: TopRatedMovies.Something.Request)
    {
        worker = TopRatedMoviesWorker()
        worker?.doSomeWork()
        
        let defaults = UserDefaults.standard
        
        if !(defaults.bool(forKey: "didFetchPopularMoviesForFirstTime")){
            defaults.set(true, forKey: "didFetchPopularMoviesForFirstTime")
            worker?.downloadTopRatedMovies(lang: "en-US", page: 1, category: .popular, completion2: {success in
                
                if success{
                    let response = TopRatedMovies.Something.Response()
                    self.presenter?.presentSomething(response: response)
                }
                
            })
        }else{
            worker?.fetchMovies(category: .popular, fetchedMovies: {
                success in
                if success{
                    let response = TopRatedMovies.Something.Response()
                    self.presenter?.presentSomething(response: response)
                }
            })
        }
        
        
       
        
       
        
    }
    
    func callAPI(with page: Int, category: MovieCategory){
        worker?.downloadTopRatedMoviesWithoutLag(lang: "en-US", page: page, category: category, completion2: {success in
            if success{
                let response = TopRatedMovies.Something.Response()
                self.presenter?.presentSomething(response: response)
            }
            
        })
        
    }
}
