//
//  TopRatedMoviesRouter.swift
//  MovieApp
//
//  Created by Thanos on 23/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TopRatedMoviesRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToDetailViewController()
    func routeToViewController()
}

protocol TopRatedMoviesDataPassing
{
  var dataStore: TopRatedMoviesDataStore? { get }
  var movie: Movie?{ get set }
  var category: MovieCategory? { get set }
  var destinationViewController: UIViewController? { get set }
  var topRatedMovies: [Movie]? { get set }
    var pageCount: Int? { get set }
}

class TopRatedMoviesRouter: NSObject, TopRatedMoviesRoutingLogic, TopRatedMoviesDataPassing
{
  weak var viewController: TopRatedMoviesViewController?
  var dataStore: TopRatedMoviesDataStore?
  var movie: Movie?
  var topRatedMovies: [Movie]?
  var category: MovieCategory?
  var destinationViewController: UIViewController?
  var pageCount: Int?
    // MARK: Routing
    
    func routeToDetailViewController() {
        let vc = UIStoryboard(name: "Main", bundle: .main).instantiateViewController(withIdentifier: "MovieDetailViewController") as! MovieDetailViewController
        vc.movie = movie
        vc.movieCategory = category
        viewController!.navigationController?.pushViewController(vc, animated: true)
    }
    
    func routeToViewController(){
        let vc = UIStoryboard(name: "Main", bundle: .main).instantiateViewController(withIdentifier: "RatedMoviesViewController") as! RatedMoviesViewController
        vc.movies = topRatedMovies ?? [Movie]()
        vc.pageCount = pageCount ?? 1
        viewController!.navigationController?.pushViewController(vc, animated: true)
    }
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: TopRatedMoviesViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: TopRatedMoviesDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
