//
//  TopRatedMoviesPresenter.swift
//  MovieApp
//
//  Created by Thanos on 23/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopRatedMoviesPresentationLogic
{
  func presentSomething(response: TopRatedMovies.Something.Response)
}

class TopRatedMoviesPresenter: TopRatedMoviesPresentationLogic
{
  weak var viewController: TopRatedMoviesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TopRatedMovies.Something.Response)
  {
    let viewModel = DatabaseManager.popularMovies
    viewController?.displaySomething(viewModel: viewModel)
  }
}
